"""Download task status vocabulary."""
PENDING = 'PENDING'
DOWNLOADING = 'DOWNLOADING'
PROCESSING = 'PROCESSING'
COMPLETED = 'COMPLETED'
ERROR = 'ERROR'
CANCELLED = 'CANCELLED'
ACTIVE = (PENDING, DOWNLOADING, PROCESSING)
ALL = (*ACTIVE, COMPLETED, ERROR, CANCELLED)
